import type { NextPage } from 'next'
import Head from 'next/head'

import Contact from '../src/components/contact'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Contact MFE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Contact />
    </>
  )
}

export default Home
